# curl => unzip => assemble
desc "Setup target platform"
task :setup do
  urls = ENV["urls"].split(",").map{ |t| t.strip }
  dest = ENV["dest"]
  
  dest_download_folder = File.join(dest, "downloads")
  dest_work_folder = File.join(dest, "work")
  dest_target_platform_folder = File.join(dest, "targetPlatform")
  
  [dest_download_folder, dest_work_folder, dest_target_platform_folder].each {|d| mkdir_p d}
  
  urls.each do |url|
    dest_download_file = File.join(dest_download_folder, File.basename(url))
    dest_work_folder = File.join(dest_download_folder, File.basename(url))
    Rake::Task[:download].invoke(url, File.join(dest_download_folder, dest_download_file))
    Rake::Task[:unzip].invoke(dest_download_file, File.join(dest_download_folder, file))
    
    
    Rake::Task[:download].reenable
  end
end

desc "Download artifact with specified url and destination."
task :download, :url, :dest_file do |t, args|
  url = args[:url]
  dest_file = args[:dest_file]
  
  puts "Downloading artifact #{url} to #{dest_file}"
  sh "curl -L #{url} -o #{dest_file} -b cookies.txt -s"
end

desc "Unzip all downloaded files into a destination."
task :unzip, :zip_file, :dest do |t, args|
  sh "unzip #{args[:zip_file]} -d #{args[:dest]}"
end

desc "Assemble all plugins and features into a destination."
task :assemble, :zip_file, :dest, :needs => :unzip do |t, args|
end

